00:00:00.000322 main     VirtualBox COM Server 6.1.16 r140961 win.amd64 (Oct 16 2020 16:33:17) release log
00:00:00.000325 main     Log opened 2020-11-23T17:42:01.914467500Z
00:00:00.000326 main     Build Type: release
00:00:00.000329 main     OS Product: Windows 10
00:00:00.000330 main     OS Release: 10.0.18363
00:00:00.000330 main     OS Service Pack: 
00:00:00.080299 main     DMI Product Name: 20L6S9U200
00:00:00.086933 main     DMI Product Version: ThinkPad T480
00:00:00.086940 main     Firmware type: BIOS
00:00:00.086959 main     Host RAM: 32426MB (31.6GB) total, 26199MB (25.5GB) available
00:00:00.086964 main     Executable: C:\Program Files\Oracle\VirtualBox\VBoxSVC.exe
00:00:00.086964 main     Process ID: 4540
00:00:00.086965 main     Package type: WINDOWS_64BITS_GENERIC
00:00:00.146735          VirtualBox: object creation starts
00:00:00.146915          Home directory: 'F:\Portable-VirtualBox\data\.VirtualBox'
00:00:00.147006          Installed Drivers:
00:00:00.150990            C:\WINDOWS\system32\DRIVERS\VBoxNetLwf.sys (Version: 6.1.16.40961)
00:00:00.151348            C:\WINDOWS\system32\DRIVERS\VBoxUSBMon.sys (Version: 6.1.16.40961)
00:00:00.151679            C:\WINDOWS\system32\DRIVERS\VBoxDrv.sys (Version: 6.1.16.40961)
00:00:00.152414            C:\WINDOWS\System32\drivers\VBoxNetAdp6.sys (Version: 6.1.16.40961)
00:00:00.156850          Loading settings file "F:\Portable-VirtualBox\data\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
00:00:00.158445          usbLibGetDevices: Starting USB device enumeration
00:00:00.159825          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&d1fe901&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
00:00:00.159870          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&d1fe901&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 7
00:00:00.159907          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&d1fe901&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 8
00:00:00.159943          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&d1fe901&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 9
00:00:00.160949          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#4&d1fe901&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 15
00:00:00.161058          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&d2d70c4&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 1
00:00:00.161092          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&d2d70c4&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 2
00:00:00.161126          Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&d2d70c4&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
00:00:00.162188          usbLibGetDevices: Found 10 USB devices, 0 captured
00:00:00.162264          USB: Unknown USB device detected (idVendor: 0x06cb, idProduct: 0x009a)
00:00:00.162275          USB: Unknown USB device detected (idVendor: 0x0bda, idProduct: 0x0316)
00:00:00.162289          USB: Unknown USB device detected (idVendor: 0x13d3, idProduct: 0x56a6)
00:00:00.162309          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x0a2b)
00:00:00.162322          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x0ac9)
00:00:00.162332          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x0aca)
00:00:00.162339          USB: Unknown USB device detected (idVendor: 0x8087, idProduct: 0x0af1)
00:00:00.247764          HostDnsMonitor: initializing
00:00:00.256075          HostDnsMonitor: updating information
00:00:00.256100          HostDnsMonitor: old information
00:00:00.256101            no server entries
00:00:00.256102            no domain set
00:00:00.256102            no search string entries
00:00:00.256103          HostDnsMonitor: new information
00:00:00.256103            server 1: 127.0.0.1
00:00:00.256104            domain: ni.corp.natinst.com
00:00:00.256104            no search string entries
00:00:00.352582          VD: VDInit finished with VINF_SUCCESS
00:00:00.354834          Loading settings file "F:\Portable-VirtualBox\data\.VirtualBox\Machines\LinuxLive\LinuxLive.vbox" with version "1.14-windows"
00:00:00.357701          Loading settings file "F:\Portable-VirtualBox\data\.VirtualBox\Machines\Debug\Debug.vbox" with version "1.14-windows"
00:00:00.366989          OCI: Local config file 'F:\Portable-VirtualBox\data\.VirtualBox\oci_config' does not exist
00:00:00.367079          OCI: Original config file 'C:\Users\inthirua\.oci\config' does not exist
00:00:00.367080          OCI: Reading profiles finished with status ERROR_SUCCESS
00:00:00.367087          ExtPack: Created cloud provider 'OCI' (hrc=ERROR_SUCCESS)
00:00:00.367108          VirtualBox: object created
00:00:00.845195          Launched VM: 76922592 pid: 8692 (0x21f4) frontend: GUI/Qt name: LinuxLive
00:00:04.411951          Load [C:\Program Files\Oracle\VirtualBox\ExtensionPacks\Oracle_VM_VirtualBox_Extension_Pack\win.amd64\VBoxHostWebcam.DLL] vrc=VINF_SUCCESS
00:00:04.646360          ERROR [COM]: aRC=VBOX_E_IPRT_ERROR (0x80bb0005) aIID={85632c68-b5bb-4316-a900-5eb28d3413df} aComponent={SessionMachine} aText={Saved screenshot data is not available (VERR_NOT_SUPPORTED)}, preserve=false aResultDetail=-37
00:01:00.190243          Saving settings file "F:\Portable-VirtualBox\data\.VirtualBox\Machines\LinuxLive\LinuxLive.vbox" with version "1.14-windows"
00:01:00.861210          Saving settings file "F:\Portable-VirtualBox\data\.VirtualBox\Machines\LinuxLive\LinuxLive.vbox" with version "1.14-windows"
00:01:06.454500 main     VirtualBox: object deletion starts
00:01:06.848099 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'F:\Portable-VirtualBox\data\.VirtualBox\Machines\LinuxLive\HardDisks/LinuxLive.vmdk' cannot be closed because it is still attached to 2 virtual machines}, preserve=false aResultDetail=0
00:01:06.854318 main     HostDnsMonitor: shutting down ...
00:01:06.859813 main     HostDnsMonitor: shut down
00:01:06.868392 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={d0a0163f-e254-4e5b-a1f2-011cf991c38d} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
00:01:06.873606 main     VirtualBox: object deleted
